#! /bin/sh
### BEGIN INIT INFO
# Provides:          adrift
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: spawn fcgi for adrift
# Description:
### END INIT INFO

case "$1" in
  start)
    spawn-fcgi -d /home/adrift/adrift -f /home/adrift/adrift/server.py -a 127.0.0.1 -p 9002
    ;;
  restart|reload|force-reload)
    kill `pgrep -f "python /home/adrift/adrift/server.py"`
    sleep 0.5
    spawn-fcgi -d /home/adrift/adrift -f /home/adrift/adrift/server.py -a 127.0.0.1 -p 9002
    ;;
  stop)
    kill `pgrep -f "python /home/adrift/adrift/server.py"`
    ;;
  *)
    echo "Usage: $0 start|restart|stop" >&2
    exit 3
    ;;
esac

:
